package com.a5.group18.enumerated;

/**
 * @author Tim Shi
 * @version 1.0
 */
public enum Campus {
    AUCKLAND_ONLINE, CITY, EPSOM, EXTRAMURAL, GRAFTON, KAWAKAWA, LEIGH_MARINE, NEWMARKET, ONLINE, OVERSEAS, ROTORUA,
    SOUTH_AUCKLAND, TAI_TOKERAU, TĀMAKI, UNSPECIFIED_WITHIN_NEW_ZEALAND, WAIHEKE_ISLAND, WAIKATO, WEST_AUCKLAND,
    WHANGAREI;
}
