package com.a5.group18.enumerated;

/**
 * @author Tim Shi
 * @version 1.0
 */
public enum CourseComponent {
    CLINIC, FIELD_STUDIES, INDEPENDENT_STUDY, LABORATORY, LECTURE, ONLINE, PRACTICUM, PRIOR_STUDY,
    SEMINAR, STUDIO, SUPERVISION, TEAM_BASED_LEARNING, THESIS_RESEARCH, TUTORIAL, WORKSHOP
}
